Paimen/WebUI/Controllers/ConnectionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LoginManagement;
using WebUI.Models;
using System.Web.Security;
using System.IO;
using System.Diagnostics;

namespace WebUI.Controllers
{
    public class ConnectionController : Controller
    {
        private ILoginManagement _service;
        public ConnectionController()
        {
            this._service = new LoginManagementImpl();
        }

        public ViewResult LogIn()
        {
            return View();
        }

        public void LogOut()
        {
            FormsAuthentication.SignOut();
            FormsAuthentication.RedirectToLoginPage();
        }

        // GET: Connexion
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UserFromReg(string regNumber, string password="")
        {

            int regInt;
            if(!int.TryParse(regNumber, out regInt))
            {
                TempData["ErrorMessage"] = "Ce n'est pas un numéro matricule correct!";
                return RedirectToAction("LogIn");
            }

            User res = this._service.SignIn(new User {RegNumber = regInt, Password = password });
            if (res == null)
            {
                TempData["ErrorMessage"] = "Mauvais matricule!!!!!";
                return RedirectToAction("LogIn");
            }
            if (res.Profile1.Name.Equals("Admin"))
            {
                FormsAuthentication.SetAuthCookie(res.FirstName + " " + res.LastName, true);
                return RedirectToAction("UserManagement", "Admin");
            }
            return View("UserInformation",res);
        }

        public ViewResult UserInformation(User u)
        {
            return View(u);
        }


        [HttpGet]
        public void DownloadPDF(int idUser)
        {
            /*
             *             this.Response.ContentType = "application/octet-stream";
            this.Response.AddHeader("Content-Disposition", "attachment; filename=addUsers.bat");
            this.Response.OutputStream.Write(script, 0, script.Length);
            this.Response.Flush();*/

            //String filename = _service.GetPDFForStudent(idUser);
            //Debug.WriteLine(filename);
            byte[] pdf = this._service.GetPDFForStudent(idUser);
            User u = this._service.GetAllUser().FirstOrDefault(us => us.Id == idUser);
            Response.Clear();
            Response.ContentType = "application/pdf";
            Response.AppendHeader("Content-Disposition", "attachment; filename=login_" + u.FirstName + "_" + u.LastName + "_" + ".pdf");
            Response.OutputStream.Write(pdf, 0, pdf.Length);
            Response.End();
        }
    }
}

Paimen/WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/simple-sidebar.css" rel="stylesheet" type="text/css"/>
    <script src="~/Scripts/Utils.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="padding-right:20px;">
            <div class="navbar-header">
                @Html.ActionLink("Login Management", "LogIn", "Connection", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                       
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="~/Connection/Logout">Logout&nbsp;<span class="glyphicon glyphicon-log-out"></span></a></li>
                </ul>
        </div>
    </div>

    <div id="wrapper" class="sb">
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li id="UserManagement">
                    <a href="~/Admin/UserManagement">User Management</a>
                </li>
                <li  id="ProfileManagement">
                    <a href="~/Admin/ProfileManagement">Profile Management</a>
                </li>
                <li id="SoftwareManagement">
                    <a href="~/Admin/SoftwareManagement">Software Management</a>
                </li>
            </ul>
        </div>

        <div id="page-content-wrapper" class="container-fluid body-content">
            @if (TempData["SuccessMessage"] != null) //check for a message in the TempData, at this point, the message should come from the edit/delete method of the AdminController
            {
                <div class="alert alert-success">@TempData["SuccessMessage"]</div>
            }
            @if (TempData["ErrorMessage"] != null) //check for a message in the TempData, at this point, the message should come from the edit/delete method of the AdminController
            {
                <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
            }
            @RenderBody()
        </div>
    </div>
</body>
</html>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
<script src="~/Scripts/DataTables/dataTables.bootstrap.js"></script>

Paimen/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/FileInput.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/Utils.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Login Management", "LogIn", "Connection", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        
                    </li>
                </ul>
            </div>
        </div>
    </div>
    @if (TempData["SuccessMessage"] != null) //check for a message in the TempData, at this point, the message should come from the edit/delete method of the AdminController
    {
        <div class="alert alert-success">@TempData["SuccessMessage"]</div>
    }
    @if (TempData["ErrorMessage"] != null) //check for a message in the TempData, at this point, the message should come from the edit/delete method of the AdminController
    {
        <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
    }
    <div class="container body-content">
        @RenderBody()
    </div>

    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>